openapi: 3.0.1
info:
  title: RCP Partner API
  description: RCP Partner API allows managing data related with a single partner
    through a simple API that have access to any data related to that partner.
  contact:
    email: info@remotecarepartners.com
  version: 0.1.0
servers:
- url: https://cloud.hub.remotecarepartners.com/{environment}/netcomp_rcp/rpc/partners/api/v1
  variables:
    environment:
      default: prod
      enum:
      - dev
      - qa
      - prod
tags:
- name: organization
  description: Organizations
- name: office
  description: Office (aka Branch)
- name: patient
  description: Patient
paths:
  /organization:
    get:
      tags:
      - organization
      summary: Finds organizations
      description: Find organizations according to optional filter parameters
      operationId: getOrganizations
      security:
      - partner_auth:
        - read:organization
    put:
      tags:
      - organization
      summary: Update an existing organization
      operationId: updateOrganization
      security:
      - partner_auth:
        - write:organization
        - read:organization
    post:
      tags:
      - organization
      summary: Add a new organization to the given partner
      operationId: addOrganization
      security:
      - partner_auth:
        - write:organization
        - read:organization
  /organization/{organizationUid}:
    get:
      tags:
      - organization
      summary: Find organization by UID
      description: Returns a single organization
      operationId: getOrganization
      security:
      - partner_auth:
        - read:organization
    delete:
      tags:
      - organization
      summary: Deletes an organization
      operationId: deleteOrganization
      security:
      - partner_auth:
        - write:organization
        - read:organization
  /office:
    get:
      tags:
      - office
      summary: Finds offices
      description: Find offices according to optional filter parameters
      operationId: getOffices
      security:
      - partner_auth:
        - read:office
    put:
      tags:
      - office
      summary: Update an existing office
      operationId: updateOffice
      security:
      - partner_auth:
        - write:office
        - read:office
    post:
      tags:
      - office
      summary: Add a new office to the given partner
      operationId: addOffice
      security:
      - partner_auth:
        - write:office
        - read:office
  /office/{officeUid}:
    get:
      tags:
      - office
      summary: Find office by UID
      description: Returns a single office
      operationId: getOffice
      security:
      - partner_auth:
        - read:office
    delete:
      tags:
      - office
      summary: Deletes an office
      operationId: deleteOffice
      security:
      - partner_auth:
        - write:office
        - read:office
  /patient:
    get:
      tags:
      - patient
      summary: Finds patients
      description: Find patients according to optional filter parameters
      operationId: getPatients
      security:
      - partner_auth:
        - read:patient
    put:
      tags:
      - patient
      summary: Update an existing patient
      operationId: updatePatient
      security:
      - partner_auth:
        - write:patient
        - read:patient
    post:
      tags:
      - patient
      summary: Add a new patient to the given partner
      operationId: addPatient
      security:
      - partner_auth:
        - write:patient
        - read:patient
  /patient/{patientUid}:
    get:
      tags:
      - patient
      summary: Find patient by UID
      description: Returns a single patient
      operationId: getPatient
      security:
      - partner_auth:
        - read:patient
    delete:
      tags:
      - patient
      summary: Deletes an patient
      operationId: deletePatient
      security:
      - partner_auth:
        - write:patient
        - read:patient
components:
  securitySchemes:
    partner_auth:
      type: http
      scheme: basic
