openapi: 3.0.1
info:
  title: RCP Partner Webhook API
  description: RCP Partner Webhook API allows receiving asynchronous information from
    RCP.
  contact:
    email: info@remotecarepartners.com
  version: 0.1.0
servers:
- url: https://{customerUrl}
  variables:
    customerUrl:
      description: Customer Webhook URL
      default: rennovahealth.com/rpcwebhook
tags:
- name: order
  description: Order
  externalDocs:
    description: GitHub
    url: https://github.com/netscale-technologies/netcomp_rcp_doc/blob/prod/doc/orders.md
paths:
  /order/{orderUid}:
    put:
      tags:
      - order
      summary: Order has been updated in RCP
      description: Typical scenario is order being processed (status = closed) and
        hub/devices being assigned to patient and sent
      operationId: updateOrder
      parameters:
      - name: orderUid
        in: path
        description: UID of updated order
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: orders-0K7F30L5AYS6UoiJWDPnLULEKvu
      requestBody:
        description: Order object that has been updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        "200":
          description: Successful operation
          content: {}
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Order not found
          content: {}
        "406":
          description: Accepted media type not supported
          content: {}
        "415":
          description: Unsupported media type
          content: {}
      security:
      - partner_auth:
        - write:order
        - read:order
      x-codegen-request-body-name: body
components:
  schemas:
    Order:
      required:
      - device_types
      - patient_uid
      - uid
      type: object
      properties:
        uid:
          type: string
          description: UID of order.
          example: orders-0K7F30L5AYS6UoiJWDPnLULEKvu
        patient_uid:
          type: string
          description: UID of valid patient.
          example: patients-0K58FX811PqZ6fFrOakaxgJZScu
        status:
          type: string
          description: Order status
          example: created
          enum:
          - created
          - closed
        name:
          type: string
          description: Contact name (overrides patient one).
          example: Jane
        surname:
          type: string
          description: Contact surname (overrides patient one).
          example: Smith
        email:
          type: string
          description: Contact email (overrides patient one).
          example: jane.smith@example.com
        phone:
          type: string
          description: Contact phone
          example: "15552106915"
        address:
          description: Contact address (overrides patient one).
          allOf:
          - $ref: '#/components/schemas/Address'
        device_types:
          type: array
          description: Ordered device types
          example:
          - hub
          - scale_bodyfat
          - pulseoximeter
          items:
            $ref: '#/components/schemas/OrderDevice'
    Address:
      required:
      - street
      type: object
      properties:
        street:
          type: string
          description: Street name
          example: 1265 Borregas Ave.
        code:
          type: string
          description: ZIP code
          example: "94086"
        city:
          type: string
          description: City name
          example: Sunnyvale
        state:
          type: string
          description: State name
          example: CA
        country:
          type: string
          description: Country name
          example: USA
    OrderDevice:
      type: string
      example: hub
      enum:
      - hub
      - scale_bodyfat
      - scale_only_weight
      - heartrate
      - pulseoximeter
      - bpm_small_cuff
      - bpm_medium_cuff
      - bpm_large_cuff
      - glucose
      - thermometer
      - spirometer
    Error:
      required:
      - code
      - description
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: invalid_parameter
        description:
          type: string
          description: Error description in English
          example: 'Invalid parameter found: test'
  securitySchemes:
    partner_auth:
      type: http
      scheme: basic
